
name: Create Release

on:
  push:
    tags: 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: packageReleaseCurrentOS

    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        path: build/packages/*.zip

    - uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        files: builds/packages/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
